sudo: required
language: python
python:
- '3.6'
services:
- mongodb
before_install:
- printenv | grep -E '^TRAVIS_' > .env
- sudo apt-get install -y build-essential wget git
- sudo apt-get install -y python3-pip python3-cffi
- pip install -U pip setuptools
- pip install Sphinx
- pip install sphinx_rtd_theme
install:
- python setup.py install
script:
- python setup.py test
after_success:
- cd plugin_packaging && ./build_plugin.sh && cd ..
deploy:
  - provider: releases
    api_key: ${TRAVIS_GH_TOKEN}
    file: plugin_packaging/travisSHARK_plugin.tar
    skip_cleanup: true
    on:
      repo: smartshark/travisSHARK
      tags: true
  - provider: pages
    github-token: ${TRAVIS_GH_TOKEN}
    local-dir: "$TRAVIS_BUILD_DIR/docs/build"
    skip_cleanup: true
    on:
      branch: master
